import Head from "next/head";
import Image from "next/image";
import ImageUploader from "../components/ImageUploader";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="cont">
          <div className="box">
            <ImageUploader />
          </div>
        </div>
      </main>
    </div>
  );
}
